---
title: "Atividade 21 - MAT0222"
subtitle: "Álgebra Linear II"
date: "08/07/2020"
output: pdf_document
---
# Exercício 5 da lista 7

Do enunciado temos que $T:\mathbb{C}^2\longrightarrow\mathbb{C}^2$ tal que $T(1+i,0)=(1+i,2)$ e $T(i,1)=(i,i)$.

Seja $C=\{(1,0),(0,1)\}$ a base canônica de $\mathbb{C}^2$, sabemos então que $C$ é uma base ortonormal.

1. Econtraremos $T(1,0)$ e $T(0,1)$

Para $T(1,0)$
\begin{align*}
T(1,0)&=xT(1+i,0)+yT(i,1)\implies(1,0)=x(1+i,0)+y(i,1),\hspace{0.5cm}x,y\in\mathbb{C}\\
y&=0 \text{ e } x(1+i)=1\implies (a+bi)(1+i)=1,\text{para }x=a+bi,\hspace{0.5cm}a,b\in \mathbb{R}
\end{align*}
Desenvolvendo $(a+bi)(1+i)=1\implies a+bi+ai-b=1$, chegamos ao seguinte sistema linear,
$$\begin{cases}
a-b=1\\a+b=0
\end{cases}\implies\begin{cases}a=\frac{1}{2}\\b=-\frac{1}{2}\end{cases}$$
Desta forma,
\begin{align*}
T(1,0)&=\left(\frac{1}{2}-\frac{1}{2}i\right)T(1+i,0)=\left(\frac{1}{2}-\frac{1}{2}i\right)(1+i,2)\\
&=\left(\frac{1}{2}-\frac{1}{2}i+\frac{1}{2}i+\frac{1}{2},1-i\right)=(1,1-i)
\end{align*}

Para $T(0,1)$
\begin{align*}
T(0,1)&=xT(1+i,0)+yT(i,1)\implies(0,1)=x(1+i,0)+y(i,1),\hspace{0.5cm}x,y\in\mathbb{C}\\
y&=1 \implies (a+bi)(1+i)+i=0,\text{para }x=a+bi,\hspace{0.5cm}a,b\in \mathbb{R}
\end{align*}
Desenvolvendo $(a+bi)(1+i)+i=0\implies a+bi+ai-b+i=0$ obtemos
$$\begin{cases}
a-b=0\\a+b+1=0
\end{cases}\implies\begin{cases}a=-\frac{1}{2}\\b=-\frac{1}{2}\end{cases}$$
Então,
\begin{align*}
T(0,1)&=\left(-\frac{1}{2}-\frac{1}{2}i\right)(1+i,2)+(i,i)\\
&=\left(-\frac{1}{2}-\frac{1}{2}i-\frac{1}{2}i+\frac{1}{2},-1-i\right)+(i,i)\\
&=(-i,-i-1)+(i,i)=(0,-1)
\end{align*}
Assim temos que
$$T(1,0)=(1,1-i)\hspace{1cm}T(0,1)=(0,-1)$$
Podemos então encontrar $[T]_C$

$$
[T]_C=\begin{bmatrix}
1&0 \\
1-i&-1
\end{bmatrix}
$$
2. Encontrar $[T^*]_C$

Para determinarmos a matriz desejada, vamos primeiro relembrar que se $C$ é uma base ortonormal de $\mathbb{C}^2$, então sabemos que 
$$
[T^*]_C=\overline{[T]_C^t}
$$
Então sabemos calcular $[T^*]_C$, já que conhecemos $[T]_C$
$$
\text{Se }[T]_C=\begin{bmatrix}
1&0 \\
1-i&-1
\end{bmatrix} \text{ então } [T^*]_C=\overline{[T]_C^t}=\begin{bmatrix}
1&1+i \\
0&-1
\end{bmatrix}
$$
Vamos considerar agora, $B=\{v_1=(1+i,0),v_2=(i,1)\}$ base de $\mathbb{C}^2$. Note que para econtrarmos $[T^*]_B$, basta conhecermos $T^*v_1$ e $T^*v_2$.
Para calcularmos a aplicação de $T$ nos vetores da base, usaremos a matriz $[T^*]_C$, já calculada acima.
$$
[T^*]_C\cdot v_1=\begin{bmatrix} 1&1+i \\ 0&-1\end{bmatrix}
\begin{bmatrix} 1+i \\ 0\end{bmatrix}=
\begin{bmatrix} 1+i \\ 0\end{bmatrix}_C
$$
$$
[T^*]_C\cdot v_2=\begin{bmatrix}1&1+i \\0&-1\end{bmatrix}
\begin{bmatrix} i \\ 1 \end{bmatrix}=
\begin{bmatrix} 2i+1 \\ -1 \end{bmatrix}_C
$$
Conseguimos obter os valores desejados, porém não estão na base $B$. Então logicamente, a tarefa agora será encontrar $[u_1]_B=(a,b)_B=(1+i,0)_C$ e $[u_2]_B=(c,d)_B=(2i+1,-1)_C$

Para $[u_1]_B$ é fácil ver que $[u_1]_C=v_1 \implies [u_1]_B=(1,0)$

Para $[u_2]_B$
$$c(1+i,0)+d(i,1)=(2i+1,-1)\implies d=-1$$
Então,
\begin{align*}
c(1+i)-i&=2i-1\\
c(1+i)&=3i-1\\
c&=\frac{3i-1}{i+1}=\frac{(3i+1)(1-i)}{2}=\frac{3i+1+3-i}{2}\\
c&=\frac{4+2i}{2}=2+i
\end{align*}

Desta forma temos que $[u_2]_B=(2+i,-1)_B$, logo podemos escrever

$$
[T^*]_B=\begin{bmatrix} 1 & 2+i \\ 0 & -1\end{bmatrix}
$$
E o exercícios está terminado.










